name: Generate Snake

on:
  # สั่งให้ทำงานอัตโนมัติทุกๆ 24 ชั่วโมง
  schedule:
    - cron: "0 0 * * *"
  
  # ยินยอมให้กดสั่งรันระบบเองมือได้ด้วย
  workflow_dispatch:
  
  # สั่งให้ทำงานทุกครั้งที่มีการอัปเดตโค้ดในหน้าโปรไฟล์
  push:
    branches:
    - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # 1. ดึงโค้ดจากเครื่องมือของเจ้าของตัวจริง (Platane/snk) เพื่อสร้างแอนิเมชันงู
      - name: generate-github-contribution-grid-snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Hypnoseng
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # 2. นำไฟล์รูปงูที่ได้ อัปโหลดขึ้นไปเก็บไว้ในคลังของเรา (ใน Branch ชื่อ output)
      - name: push github-contribution-grid-snake to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
